source "https://rubygems.org"

gem 'sinatra'
gem 'rspec'
gem 'capybara'
gem 'simplecov', require: false
gem 'simplecov-console', require: false
gem 'pg'

group :development, :test do
  gem "rubocop", "0.79.0"
end
